### ISSUE TITLE
CampJS in NZ

### ISSUE THREAD

**Issue by Unfocused** [JavaScript-NZ/Society-Meetings#1]
A CampJS in NZ would be pretty cool. Australia has this!

**Comment by phenomnomnominal** [comment]
+1

**Comment by PrototypeAlex** [comment]
I was chatting to @timoxley about this at nodeconf, he was open to us picking his brain about what's needed, which would be a huge help in kicking this off. Would be cool if there was a chance of sharing branding and becoming a branch of the official campjs?

**Comment by Unfocused** [comment]
Yea, I think officially being a branch of CampJS would have it's benefits:
- Recognition of the brand - easier to get people there
- Less work for us, as various things are already set out

**Comment by timoxley** [comment]
@PrototypeAlex 100% cool with it. Let's do this.

**Comment by buildmaster** [comment]
I think rails camp have done one at Kaitoke before?

**Comment by parndt** [comment]
Yeah, we've (@nzruby) had two camps at Kaitoke. You could ask @terrcin about Kaitoke one specifically, otherwise I'm happy to help out with ideas or other more practical things. I'm sure there's a lot of potential duplication between our two societies, so it makes sense to collaborate sometimes. Let me know! :smile:

**Comment by wrumsby** [comment]
Put this idea on hold. The idea was raised of a grass-roots conference. Revisit this in a few months time.

**Comment by parndt** [comment]
@wrumsby cool, I actually saw (and am watching) the discussion at the meeting.

**Comment by bnolan** [comment]
Hey we should do this!

**Comment by PrototypeAlex** [comment]
@bnolan are you interested in helping organising one? 

I'm keen to help out where I can, but that's probably just through helping with the accounting and moral support 📣.

If we do decided to have one, it might be best to set it up to be after March 2017, since that's when nz.js(con) is; we could do it beforehand, but it'd push us over the GST threshold for the year.

If we have someone interested in organising, then we could reopen this issue to kick things off, or at least raise it in the next committee meeting.
