### ISSUE TITLE
Nominations and Vote for Treasurer

### ISSUE THREAD

**Issue by buildmaster** [JavaScript-NZ/Society-Meetings#10]
we need to nominate and vote officially for treasurer. 

currently unofficially @PrototypeAlex whom I nominate again

**Comment by Unfocused** [comment]
Seconded for @PrototypeAlex

**Comment by Unfocused** [comment]
@PrototypeAlex - could you provide a short bio/blurb/whatever. Just something to give people context as to why you think you should be voted in.

**Comment by PrototypeAlex** [comment]
No worries @Unfocused.

I'm Alex, I currently run NodeBots New Zealand and the node.js meetup in Wellington. I'm a node developer during the day, and I help teach people robotics with JavaScript by night (and weekends).

I initially raised my hand to be the treasurer because at the time of the creation of the society, I was in discussions with various companies regarding sponsorship for NodeBots. Since then I've raised 5k for NodeBots, and $1,200 for the node.js meetup in Wellington. 

I'm more than happy to give someone else the opportunity to be treasurer, as it's a unique learning experience, but I'm also happy to continue doing the accounts.

Cheers,
a

**Comment by wrumsby** [comment]
Alex appointed treasurer with 9 :+1: votes.
