### ISSUE TITLE
How shall we handle membership renewals.

### ISSUE THREAD

**Issue by PrototypeAlex** [JavaScript-NZ/Society-Meetings#37]
When it comes up to July, we'll have memberships expiring, which will require renewal. 

Up until now, we've been invoicing through Xero, so sending out renewal's might be a bit repetitive (unless there's an API someone might know about 😉)

Open to suggestions on how we approach this.

**Comment by jenofdoom** [comment]
Update as per committee meeting 21/3/16: @buildmaster to put forwards a proposal to be voted upon at the next AGM

**Comment by veb** [comment]
we could tie this in with the website v2 discussion, because members will sign up, and manually assigned the membership flag. if we were to automate this through a payment gateway, and using API from Xero - http://developer.xero.com/code-samples/libraries/node-js/ for example, we could have everything nice and shiny.

:)

**Comment by buildmaster** [comment]
As decided we're moving to a recurring invoice model. myself and @PrototypeAlex will start moving existing members from 1st of Month
